#!/bin/bash

AutosomeDefault=F
BfileDefault=/home/wheelerlab2/Data/MESA_dbGaP_55081/phg000071.v2.NHLBI_SHARE_MESA.genotype-calls-matrixfmt.c1/SHARE_MESA_c1
OutputDirDefault=~/QC
GenotypingThresholdDefault=0.01
while :
do
    case "$1" in
      -a | --autosome) #same as normal plink - Path to all files and the shared prefix
	        Autosome=T 
	        shift 1
	        ;;
      -b | --bfile) #same as normal plink - Path to all files and the shared prefix
	        BFile="$2"  
	        shift 2
	        ;;
      --bim) #/path/to/file.bim
        	  BimFile="$2"
	        shift 2
	        ;;
      --bed) #/path/to/file.bed
      	  	BedFile="$2"
	        shift 2
	        ;;
      --fam) #/path/to/file.fam
      	 	FamFile="$2"
	        shift 2
	        ;;
      -k | --keep) #list of individuals you would like to keep. mutually exclusive with remove
      	  	KeepList="$2"
	        Prefilter=keep
		shift 2
	        ;;
      -gt | --genothreshold) #threshold to filter geotyping rate by
      	  	GenotypingThreshold="$2"
	        shift 2
	        ;;
      -o | --output) #directory where you'd like to send all your QC folders - will be folder hierarchy
          	Outputdir="$2"
	        shift 2
	        ;;
      -r | --remove) #list of individuals you would like to remove
      	  	RemoveList="$2"
		Prefilter=remove
	        shift 2
	        ;;
      -*) #unknown 
      		echo "Error: Unknown option: $1" >&2
	        exit 1
	        ;;
      *)  # No more options
         	shift
	        break
	        ;;
     esac
done

echo "Using bam file ${BimFile:=$BFile.bim}"
echo "Using bed file ${BedFile:=$BFile.bed}"
echo "Using fam file ${FamFile:=$BFile.fam}"

if [ ! -e "${BimFile}" ] || [ ! -e "${FamFile}" ] || [ ! -e "${BedFile}" ]
then
  echo "Warning: One or more files does not exist. Exiting."
  exit 1
fi

if [ ! -d "${OutputDir:=$OutputDirDefault}" ]
then
  mkdir "${OutputDir}"
  mkdir "${OutputDir}"/QCstats
  mkdir "${OutputDir}"/QCStep1
  mkdir "${OutputDir}"/QCStep2
  mkdir "${OutputDir}"/QCStep3
  mkdir "${OutputDir}"/QCStep4
  mkdir "${OutputDir}"/QCStep5
  mkdir "${OutputDir}"/QCStep5/QCStep5a
  mkdir "${OutputDir}"/QCStep5/QCStep5b
  mkdir "${OutputDir}"/QCStep5/QCStep5c
  mkdir "${OutputDir}"/QCStep5/QCStep5d
  mkdir "${OutputDir}"/QCStep5/QCStep5e
fi

#0 Optional prefiltering step for sample selection and for autosomal filtering
case "${prefilter}" in 
	keep)
		if [ "${Autosome:=AutosomeDefault}" = "F" ] 
		then
			plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --keep "${KeepList}" --make-bed --out "${OutputDir}"/QCstep0
			BedFile="${OutputDir}"/QCstep0.bed
			BimFile="${OutputDir}"/QCstep0.Bim
			FamFile="${OutputDir}"/QCstep0.Fam
		elif [ "${Autosome:=AutosomeDefault}" = "T" ] 
		then
			plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --keep "${KeepList}" --autosome --make-bed --out "${OutputDir}"/QCstep0
			BedFile="${OutputDir}"/QCstep0.bed
			BimFile="${OutputDir}"/QCstep0.Bim
			FamFile="${OutputDir}"/QCstep0.Fam
		fi
	remove)
		if [ "${Autosome:=AutosomeDefault}" = "F" ] 
		then
			plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --remove "${RemoveList}" --make-bed --out "${OutputDir}"/QCstep0
			BedFile="${OutputDir}"/QCstep0.bed
			BimFile="${OutputDir}"/QCstep0.Bim
			FamFile="${OutputDir}"/QCstep0.Fam
		elif [ "${Autosome:=AutosomeDefault}" = "T" ] 
		then
			plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --remove "${RemoveList}" --autosome --make-bed --out "${OutputDir}"/QCstep0
			BedFile="${OutputDir}"/QCstep0.bed
			BimFile="${OutputDir}"/QCstep0.Bim
			FamFile="${OutputDir}"/QCstep0.Fam
		fi
esac


#1 for determining genotyping threshold
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --missing --out "${OutputDir}"/QCStep1/QCStep1
echo "plink --bed ${BedFile} --bim ${BimFile} --fam ${FamFile} --missing --out ${OutputDir}/QCStep1/QCStep1" > "${OutputDir}"/QCStep1/command.txt
#call rate distribution check
#2 fitlers out based on genotyping threshold
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --geno "${GenotypingThreshold:=$GenotypingThresholdDefault}" --make-bed --out "${OutputDir}"/QCStep2/QCStep2
echo "plink --bed ${BedFile} --bim ${BimFile} --fam ${FamFile} --geno "${GenotypingThreshold:=$GenotypingThresholdDefault}" --make-bed --out ${OutputDir}/QCStep2/QCStep2" > "${OutputDir}"/QCStep2/command.txt
#3 For validation of missingness threshold and call rate distribution check
plink --bfile "${OutputDir}"/QCStep2/QCStep2 --missing --out "${OutputDir}"/QCStep3/QCStep3
echo "plink --bfile ${OutputDir}/QCStep2/QCStep2 --missing --out ${OutputDir}/QCStep3/QCStep3" > "${OutputDir}"/QCStep3/command.txt
#call rate distribution validation

Rscript ../Rscripts/CallRateDistribution.R -t "${GenotypingThreshold}" --QCdir "${OutputDir}"

#4 for later calculating HWE statistics
plink --bfile "${OutputDir}"/QCStep2/QCStep2 --hardy --out "${OutputDir}"/QCStep4/QCStep4
echo "plink --bfile ${OutputDir}/QCStep2/QCStep2 --hardy --out ${OutputDir}/QCStep4/QCStep4" > "${OutputDir}"/QCStep4/command.txt
#calculate HWE statistics

Rscript ../Rscripts/hwe.R --QCdir "${OutputDir}"


