#!/bin/bash

PlinkPath=/usr/local/bin

BfileDefault=~/QC/missingness_hwe_steps/05filtered_HWE
PlotIBDDefault=True
PrefilterDefault=none
OutputDirDefault=~/QC
RelatednessDefault=1
RunIBD=true
while :
do
    case "$1" in
      -b | --bfile) #same as normal plink - Path to all files and the shared prefix
	        BFile="$2"  
	        shift 2
	        ;;
      --bim) #/path/to/file.bim
         	BimFile="$2"
	        shift 2
	        ;;
      --bed) #/path/to/file.bed
      	 	BedFile="$2"
	        shift 2
	        ;;
      --fam) #/path/to/file.fam
      		FamFile="$2"
	        shift 2
	        ;;
      -k | --keep) #list of individuals you would like to keep. mutually exclusive with remove
      	  	KeepList="$2"
	        Prefilter=keep
		shift 2
	        ;;
      -o | --output) #directory where you'd like to send all your QC folders - will be folder hierarchy
         	OutputDir="$2"
	        shift 2
	        ;;
      --plotIDB-off)
	        PlotIBD=False
	      	shift 1
	        ;;
      --relatedness | --rel) #Relatedness threshold you'd like to filter by
         	Relatedness="$2"
	        shift 2
	        ;;
      --remove | -r) #list of individuals you would like to remove
      	  	RemoveList="$2"
		Prefilter=remove
	        shift 2
	        ;;
      -*) #unknown 
      	  echo "Error: Unknown option: $1" >&2
	        exit 1
	        ;;
      *)  # No more options
          shift
	        break
	        ;;
     esac
done

echo "Using bim file ${BimFile:=${BFile:=$BfileDefault}.bim}"
echo "Using bed file ${BedFile:=${BFile:=$BfileDefault}.bed}"
echo "Using fam file ${FamFile:=${BFile:=$BfileDefault}.fam}"
echo "Using Output Directory ${OutputDir:=$OutputDirDefault}"
echo "Plotting IBD: ${PlotIBD:=$PlotIBDDefault}"

if [ ! -e "${BimFile}" ] || [ ! -e "${FamFile}" ] || [ ! -e "${BedFile}" ]
then
  echo "Warning: One or more bfiles does not exist. Exiting."
  exit 1
fi

if [ ! -d "${OutputDir}" ]
then
  mkdir "${OutputDir}"
  mkdir "${OutputDir}"/relatedness_steps
  mkdir "${OutputDir}"/plots_stats
fi
if [ ! -d "${OutputDir}"/relatedness_steps ]
then
  mkdir "${OutputDir}"/relatedness_steps
fi
if [ ! -d "${OutputDir}"/plots_stats ]
then
  mkdir "${OutputDir}"/plots_stats
fi

#0 optional remove/keep samples - good for split populations
case "${Prefilter:=$PrefilterDefault}" in
	keep)
		"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --keep "${KeepList}" --make-bed --out "${OutputDir}"/missingness_hwe_steps/00filt_k
		BedFile="${OutputDir}"/missingness_hwe_steps/00keep_samples.bed
		BimFile="${OutputDir}"/missingness_hwe_steps/00keep_samples.bim
		FamFile="${OutputDir}"/missingness_hwe_steps/00keep_samples.fam
		;;
	remove)
		"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --remove "${RemoveList}" --make-bed --out "${OutputDir}"/missingness_hwe_steps/00filt_r
		BedFile="${OutputDir}"/missingness_hwe_steps/00remove_samples.bed
		BimFile="${OutputDir}"/missingness_hwe_steps/00remove_samples.bim
		FamFile="${OutputDir}"/missingness_hwe_steps/00remove_samples.fam
		;;
esac

#5a Creates a pruned list of SNP IDs for plotting on a principal components analysis
"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --indep-pairwise 50 5 0.3 --out "${OutputDir}"/relatedness_steps/01LD_prune_list
#5b create genome file for ibd chart
"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --extract "${OutputDir}"/relatedness_steps/01LD_prune_list.prune.in --genome --out "${OutputDir}"/relatedness_steps/02relatedness
#generate list of samples to remove based on relatedness

if [ "${PlotIBD}" = "True" ]
then
	Rscript ~/gwasqc_pipeline/Rscripts/ibd.R -o "${OutputDir}"/plots_stats --genome ${OutputDir}/relatedness_steps/02relatedness.genome 
fi
#5c heterozygosity check for unfiltered samples 
"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --het --out "${OutputDir}"/relatedness_steps/03het_unfiltered
#5d LD prune snps from bfiles
"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --extract "${OutputDir}"/relatedness_steps/01LD_prune_list.prune.in  --make-bed --out "${OutputDir}"/relatedness_steps/04LD_pruned
Rscript ~/gwasqc_pipeline/Rscripts/heterozygosity.R -o "${OutputDir}"/plots_stats --het "${OutputDir}"/relatedness_steps/03het_unfiltered.het --tag with_relateds

if [ $(bc <<< "${Relatedness:=$RelatednessDefault}<1") -eq 1 ]
then
	"${PlinkPath}"/plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --rel-cutoff "${Relatedness:=$RelatednessDefault}" --make-bed --out "${OutputDir}"/relatedness_steps/05without_relateds
	#5e regenerate heterozygosity estimates from filtered for validation
	"${PlinkPath}"/plink --bfile "${OutputDir}"/relatedness_steps/05without_relateds --het --out "${OutputDir}"/relatedness_steps/06het_without_relateds
	Rscript ~/gwasqc_pipeline/Rscripts/heterozygosity.R -o "${OutputDir}"/plots_stats --het "${OutputDir}"/relatedness_steps/06het_without_relateds.het --tag no_relateds
fi
