#!/bin/bash
BfileDefault=~/QC/missingness_hwe_steps/05filtered_HWE
OutputDirDefault=~/QC
RelatednessDefault=0.25
while :
do
    case "$1" in
      -b | --bfile) #same as normal plink - Path to all files and the shared prefix
	        BFile="$2"  
	        shift 2
	        ;;
      --bim) #/path/to/file.bim
         	BimFile="$2"
	        shift 2
	        ;;
      --bed) #/path/to/file.bed
      	 	BedFile="$2"
	        shift 2
	        ;;
      --fam) #/path/to/file.fam
      		FamFile="$2"
	        shift 2
	        ;;
      -o | --output) #directory where you'd like to send all your QC folders - will be folder hierarchy
         	Outputdir="$2"
	        shift 2
	        ;;
      -r | --relatedness) #Relatedness threshold you'd like to filter by
         	Relatedness="$2"
	        shift 2
	        ;;
      -*) #unknown 
      	  echo "Error: Unknown option: $1" >&2
	        exit 1
	        ;;
      *)  # No more options
          shift
	        break
	        ;;
     esac
done

echo "Using bim file ${BimFile:=${BFile:=$BfileDefault}.bim}"
echo "Using bed file ${BedFile:=${BFile:=$BfileDefault}.bed}"
echo "Using fam file ${FamFile:=${BFile:=$BfileDefault}.fam}"
echo "Using Output Directory ${OutputDir:=$OutputDirDefault}"

if [ ! -e "${BimFile}" ] || [ ! -e "${FamFile}" ] || [ ! -e "${BedFile}" ]
then
  echo "Warning: One or more bfiles does not exist. Exiting."
  exit 1
fi

if [ ! -d "${OutputDir}"/relatedness_steps ]
then
  mkdir "${OutputDir}"/relatedness_steps
fi

#5a Creates a pruned list of SNP IDs for plotting on a principal components analysis
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --indep-pairwise 50 5 0.3 --out "${OutputDir}"/relatedness_steps/01LD_prune_list
#5b Determine the relatednesss of samples
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --extract "${OutputDir}"/relatedness_steps/01LD_prune_list.prune.in --genome --min "${Relatedness:=$RelatednessDefault}" --out "${OutputDir}"/relatedness_steps/02relatedness
#generate list of samples to remove based on relatedness
Rscript ~/gwasqc_pipeline/Rscripts/ibd.R -o "${OutputDir}"/plots_stats --pihat "${Relatedness:=$RelatednessDefault}" --genome ${OutputDir}/relatedness_steps/02relatedness.genome #generate list of related samples and duplicates for removal

#5c heterozygosity check for unfiltered samples 
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --het --out "${OutputDir}"/relatedness_steps/03het_unfiltered
#5d filter out related individuals and duplicates
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --extract "${OutputDir}"/relatedness_steps/01LD_prune_list.prune.in --remove "${OutputDir}"/plots_stats/related.to.remove.txt --make-bed --out "${OutputDir}"/relatedness_steps/04without_relateds
#5e regenerate heterozygosity estimates from filtered for validation
plink --bfile "${OutputDir}"/relatedness_steps/04without_relateds --het --out "${OutputDir}"/relatedness_steps/05het_without_relateds

Rscript ~/gwasqc_pipeline/Rscripts/heterozygosity.R -o "${OutputDir}"/plots_stats -r "${Relatedness}" --filteredhet "${OutputDir}"/relatedness_steps/05het_without_relateds.het --unfilteredhet "${OutputDir}"/relatedness_steps/03het_unfiltered.het

