#!/bin/bash
BfileDefault=~/QC/QCStep2/QCStep2 
OutputDirDefault=~/QC
RelatednessDefault=0.25
while :
do
    case "$1" in
      -b | --bfile) #same as normal plink - Path to all files and the shared prefix
	        BFile="$2"  
	        shift 2
	        ;;
      --bim) #/path/to/file.bim
         	BimFile="$2"
	        shift 2
	        ;;
      --bed) #/path/to/file.bed
      	 	BedFile="$2"
	        shift 2
	        ;;
      --fam) #/path/to/file.fam
      		FamFile="$2"
	        shift 2
	        ;;
      -o | --output) #directory where you'd like to send all your QC folders - will be folder hierarchy
         	Outputdir="$2"
	        shift 2
	        ;;
      -r | --relatedness) #Relatedness threshold you'd like to filter by
         	Relatedness="$2"
	        shift 2
	        ;;
      -*) #unknown 
      	  echo "Error: Unknown option: $1" >&2
	        exit 1
	        ;;
      *)  # No more options
          shift
	        break
	        ;;
     esac
done

echo "Using bim file ${BimFile:=${BFile:=$BfileDefault}.bim}"
echo "Using bed file ${BedFile:=${BFile:=$BfileDefault}.bed}"
echo "Using fam file ${FamFile:=${BFile:=$BfileDefault}.fam}"
echo "Using Output Directory ${OutputDir:=$OutputDirDefault}"


if [ ! -d "${OutputDir}" ]
then
  echo "Warning: Missingness filtering does not exist. Please run 01-04gwas and try again. Exiting."
  exit 1
fi

if [ ! -d "${OutputDir}"/QCStep5 ]
then
  mkdir "${OutputDir}"/QCStep5
  mkdir "${OutputDir}"/QCStep5/QCStep5a
  mkdir "${OutputDir}"/QCStep5/QCSteo5b
  mkdir "${OutputDir}"/QCStep5/QCSteo5c
  mkdir "${OutputDir}"/QCStep5/QCSteo5d
  mkdir "${OutputDir}"/QCStep5/QCSteo5e
fi

#5a Creates a pruned list of SNP IDs for plotting on a principal components analysis
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --indep-pairwise 50 5 0.3 --out "${OutputDir}"/QCStep5/QCStep5a/QCStep5a
echo "plink --bed ${BedFile} --bim ${BimFile} --fam ${FamFile} --indep-pairwise 50 5 0.3 --out ${OutputDir}/QCStep5/QCStep5a/QCStep5a" > "${OutputDir}"/QCStep5/QCStep5a/command.txt
#5b filter pruned SNPs by relatedness
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --extract "${OutputDir}"/QCStep5/QCStep5a/QCStep5a.prune.in --genome --min "${Relatedness:=$RelatednessDefault}" --out "${OutputDir}"/QCStep5/QCStep5b/QCstep5b
echo "plink --bed ${BedFile} --bim ${BimFile} --fam ${FamFile} --extract ${OutputDir}/QCStep5/QCStep5a/QCStep5a.prune.in --genome --min ${Relatedness:=$RelatednessDefault} --out ${OutputDir}/QCStep5/QCStep5b/QCstep5b" > "${OutputDir}"/QCStep5/QCStep5b/command.txt

Rscript ~/gwasqc_pipeline/Rscripts/ibd.R --QCdir "${OutputDir}" #generate list of related samples and duplicates for removal

#5c heterozygosity check for unfiltered samples 
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --het --out "${OutputDir}"/QCStep5/QCStep5c/QCStep5c
echo "plink --bed ${BedFile} --bim ${BimFile} --fam ${FamFile} --het --out ${OutputDir}/QCStep5/QCStep5c/QCStep5c" > "${OutputDir}"/QCStep5/QCStep5c/command.txt
#5d filter out related individuals and duplicates
plink --bed "${BedFile}" --bim "${BimFile}" --fam "${FamFile}" --extract "${OutputDir}"/QCStep5/QCStep5a/QCStep5a.prune.in --remove "${OutputDir}"/QCstats/related.to.remove.txt --make-bed --out "${OutputDir}"/QCStep5/QCStep5d/QCStep5d
echo "plink --bed ${BedFile} --bim ${BimFile} --fam ${FamFile} --extract ${OutputDir}/QCStep5/QCStep5a/QCStep5a.prune.in --remove ${OutputDir}/QCstats/related.to.remove.txt --make-bed --out ${OutputDir}/QCStep5/QCStep5d/QCStep5d" > "${OutputDir}"/QCStep5/QCStep5d/command.txt
#5e regenerate heterozygosity estimates from filtered for validation
plink --bfile "${OutputDir}"/QCStep5/QCStep5d/QCStep5d --het --out "${OutputDir}"/QCStep5/QCStep5e/QCStep5e

Rscript ~/gwasqc_pipeline/Rscripts/heterozygosity.R --QCdir "${OutputDir}" -r "${Relatedness}"

